require("ItemTweaker_Copy_CC");

--LACTOSECROSSBOW
--Container
TweakItem("LactoseCrossbow.LCQuiver","DisplayCategory","Container");
--Misc
TweakItem("LactoseCrossbow.LCTestAttachment","DisplayCategory","Misc");
--Weapons
TweakItem("LactoseCrossbow.CrossbowBolt","DisplayCategory","WepAmmo");
TweakItem("LactoseCrossbow.CrossbowBolts","DisplayCategory","WepAmmo");
TweakItem("LactoseCrossbow.CrossbowBoltBundle","DisplayCategory","WepAmmo");
TweakItem("LactoseCrossbow.LCCrossbowBoltAluminium","DisplayCategory","WepAmmo");
TweakItem("LactoseCrossbow.LCCrossbowBoltAluminiumBundle","DisplayCategory","WepAmmo");
TweakItem("LactoseCrossbow.CrossbowUnstrung","DisplayCategory","WepPart");
TweakItem("LactoseCrossbow.CrossbowStringString","DisplayCategory","WepPart");
TweakItem("LactoseCrossbow.CrossbowStringNylon","DisplayCategory","WepPart");
TweakItem("LactoseCrossbow.ModernCrossbowUnstrung","DisplayCategory","WepPart");
TweakItem("LactoseCrossbow.CrossbowStringSteel","DisplayCategory","WepPart");
TweakItem("LactoseCrossbow.CrossbowStrungString","DisplayCategory","WepBow");
TweakItem("LactoseCrossbow.CrossbowStrungNylon","DisplayCategory","WepBow");
TweakItem("LactoseCrossbow.ModernCrossbowStrungSteel","DisplayCategory","WepBow");
TweakItem("LactoseCrossbow.CrossbowStrungSteel","DisplayCategory","WepBow");
TweakItem("LactoseCrossbow.ModernCrossbowStrungString","DisplayCategory","WepBow");
TweakItem("LactoseCrossbow.ModernCrossbowStrungNylon","DisplayCategory","WepBow");
