require("ItemTweaker_Copy_CC");

--SCRAPARMOR
--Clothing
TweakItem("Base.Hat_ScrapHelmet","DisplayCategory","ClothN");
TweakItem("Base.Hat_ScrapHelmetopen","DisplayCategory","ClothN");
TweakItem("Base.Hat_Rebreather","DisplayCategory","ClothN");
TweakItem("Base.ScrapVest","DisplayCategory","ClothN");
TweakItem("Base.ScrapGloves","DisplayCategory","ClothN");
TweakItem("Base.ScrapPads","DisplayCategory","ClothN");
TweakItem("Base.ScrapKilt","DisplayCategory","ClothN");
TweakItem("Base.ScrapKiltPainted1","DisplayCategory","ClothN");
TweakItem("Base.ScrapKiltPainted2","DisplayCategory","ClothN");
TweakItem("Base.ScrapKiltPainted3","DisplayCategory","ClothN");
TweakItem("Base.ScrapBoots","DisplayCategory","ClothN");
--Literature
TweakItem("SArmor.ArmorMag1","DisplayCategory","LitR");
TweakItem("SArmor.ArmorMag2","DisplayCategory","LitR");
--Weapons
TweakItem("Base.ScrapShield","DisplayCategory","WepShield");
TweakItem("Base.ScrapShieldPainted1","DisplayCategory","WepShield");
TweakItem("Base.ScrapShieldPainted2","DisplayCategory","WepShield");
TweakItem("Base.ScrapShieldPainted3","DisplayCategory","WepShield");
TweakItem("Base.CarDoorShield","DisplayCategory","WepShield");
TweakItem("Base.CarDoorShield1","DisplayCategory","WepShield");
TweakItem("Base.CarDoorShield2","DisplayCategory","WepShield");
