require("ItemTweaker_Copy_CC");

--SGUNS
--Weapons
TweakItem("SGuns.ShrapnelShell","DisplayCategory","WepAmmo");
TweakItem("SGuns.SBBox","DisplayCategory","WepAmmo");
TweakItem("SGuns.SRMagazine","DisplayCategory","WepAmmo");
TweakItem("SGuns.SBullets","DisplayCategory","WepAmmo");
TweakItem("SGuns.SSMGMagazine","DisplayCategory","WepAmmo");
TweakItem("SGuns.SSBox","DisplayCategory","WepAmmo");
TweakItem("SGuns.GlassBomb","DisplayCategory","WepBomb");
TweakItem("SGuns.HPB","DisplayCategory","WepBomb");
TweakItem("SGuns.NailBomb","DisplayCategory","WepBomb");
TweakItem("SGuns.HPS","DisplayCategory","WepFire");
TweakItem("SGuns.HP","DisplayCategory","WepFire");
TweakItem("SGuns.HDBS","DisplayCategory","WepFire");
TweakItem("SGuns.SR","DisplayCategory","WepFire");
TweakItem("SGuns.SRB","DisplayCategory","WepFire");
TweakItem("SGuns.SARBO","DisplayCategory","WepFire");
TweakItem("SGuns.SSMGUnfolded","DisplayCategory","WepFire");
TweakItem("SGuns.SSMGFolded","DisplayCategory","WepFire");
TweakItem("SGuns.SlamFire","DisplayCategory","WepFire");
TweakItem("SGuns.SAR","DisplayCategory","WepFire");
TweakItem("SGuns.SARB","DisplayCategory","WepFire");
TweakItem("SGuns.AirTank","DisplayCategory","WepPart");
TweakItem("SGuns.GunParts","DisplayCategory","WepPart");
TweakItem("SGuns.MetalScraps","DisplayCategory","WepPart");
TweakItem("SGuns.HD","DisplayCategory","WepRange");
TweakItem("SGuns.TBottle","DisplayCategory","WepRange");
