require 'Items/ProceduralDistributions'

-- DoomsdayPreppers1


table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 2);
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 2);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 1);
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 2);
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 2);
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, 4);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 0.5);
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 0.2);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.DoomsdayPreppers1");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 0.2);

-- DoomsdayPreppers2

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 2);
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 2);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 1);
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 2);
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 2);
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, 4);
table.insert(ProceduralDistributions.list["GarageCarpentry"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["GarageCarpentry"].items, 0.5);
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 0.2);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.DoomsdayPreppers2");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 0.2);

-- WeaponHandlersReloaded

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "KCMweapons.WeaponHandlersReloaded");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "KCMweapons.WeaponHandlersReloaded");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 0.5);
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "KCMweapons.WeaponHandlersReloaded");
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "KCMweapons.WeaponHandlersReloaded");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 0.2);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "KCMweapons.WeaponHandlersReloaded");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 0.2);
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, "KCMweapons.WeaponHandlersReloaded");
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, 0.5);
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, "KCMweapons.WeaponHandlersReloaded");
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, 0.5);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.WeaponHandlersReloaded");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 0.5);


-- TheUltimateHuntingGuide1

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 2);
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 2);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 1);
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 2);
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 1);
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, 4);
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, 2);
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.TheUltimateHuntingGuide1");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 1);

-- TheUltimateHuntingGuide2

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 2);
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 2);
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["LivingRoomShelf"].items, 1);
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 2);
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, 2);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 1);
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, 4);
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, 2);
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.TheUltimateHuntingGuide2");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 1);

-- TheSniperGuide

table.insert(ProceduralDistributions.list["BookstoreBooks"].items, "KCMweapons.TheSniperGuide");
table.insert(ProceduralDistributions.list["BookstoreBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, "KCMweapons.TheSniperGuide");
table.insert(ProceduralDistributions.list["BookstoreMisc"].items, 0.5);
table.insert(ProceduralDistributions.list["LibraryBooks"].items, "KCMweapons.TheSniperGuide");
table.insert(ProceduralDistributions.list["LibraryBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.TheSniperGuide");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 0.5);
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, "KCMweapons.TheSniperGuide");
table.insert(ProceduralDistributions.list["CampingStoreBooks"].items, 0.5);
table.insert(ProceduralDistributions.list["CrateBooks"].items, "KCMweapons.TheSniperGuide");
table.insert(ProceduralDistributions.list["CrateBooks"].items, 0.2);
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, "KCMweapons.TheSniperGuide");
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, 2);
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, "KCMweapons.TheSniperGuide");
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, 2);
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, "KCMweapons.TheSniperGuide");
table.insert(ProceduralDistributions.list["PostOfficeBooks"].items, 0.2);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.TheSniperGuide");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 0.2);

-- KCM_Compound

table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, "KCMweapons.KCM_Compound");
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, 0.5);
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.KCM_Compound");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 2);
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, "KCMweapons.KCM_Compound");
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, 2);
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, "KCMweapons.KCM_Compound");
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, 4);
table.insert(ProceduralDistributions.list["FirearmWeapons"].junk, "KCMweapons.KCM_Compound");
table.insert(ProceduralDistributions.list["FirearmWeapons"].junk, 4);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "KCMweapons.KCM_Compound");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 0.25);
table.insert(ProceduralDistributions.list["Locker"].items, "KCMweapons.KCM_Compound");
table.insert(ProceduralDistributions.list["Locker"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "KCMweapons.KCM_Compound");
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, "KCMweapons.KCM_Compound");
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, 0.5);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.KCM_Compound");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, "KCMweapons.KCM_Compound");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, 0.5);

-- KCM_Compound02

table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, "KCMweapons.KCM_Compound02");
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, 0.5);
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.KCM_Compound02");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 1);
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, "KCMweapons.KCM_Compound02");
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, 1);
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, "KCMweapons.KCM_Compound02");
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, 4);
table.insert(ProceduralDistributions.list["FirearmWeapons"].junk, "KCMweapons.KCM_Compound02");
table.insert(ProceduralDistributions.list["FirearmWeapons"].junk, 4);
table.insert(ProceduralDistributions.list["Locker"].items, "KCMweapons.KCM_Compound02");
table.insert(ProceduralDistributions.list["Locker"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "KCMweapons.KCM_Compound02");
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 0.5);
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, "KCMweapons.KCM_Compound02");
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, 0.5);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.KCM_Compound02");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, "KCMweapons.KCM_Compound02");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, 1);

-- HandCrossbow

table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.HandCrossbow");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 2);
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, "KCMweapons.HandCrossbow");
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, 2);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "KCMweapons.HandCrossbow");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 2);
table.insert(ProceduralDistributions.list["Locker"].items, "KCMweapons.HandCrossbow");
table.insert(ProceduralDistributions.list["Locker"].items, 0.25);
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "KCMweapons.HandCrossbow");
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, "KCMweapons.HandCrossbow");
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, 1);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.HandCrossbow");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, "KCMweapons.HandCrossbow");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, 1);

-- CrossbowBoltLargeBox

table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, "KCMweapons.CrossbowBoltLargeBox");
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, 0.25);
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.CrossbowBoltLargeBox");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 0.25);
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, "KCMweapons.CrossbowBoltLargeBox");
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, 0.25);
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, "KCMweapons.CrossbowBoltLargeBox");
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, 0.25);
table.insert(ProceduralDistributions.list["FirearmWeapons"].junk, "KCMweapons.CrossbowBoltLargeBox");
table.insert(ProceduralDistributions.list["FirearmWeapons"].junk, 0.25);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "KCMweapons.CrossbowBoltLargeBox");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 0.25);
table.insert(ProceduralDistributions.list["Locker"].items, "KCMweapons.CrossbowBoltLargeBox");
table.insert(ProceduralDistributions.list["Locker"].items, 0.25);
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "KCMweapons.CrossbowBoltLargeBox");
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 0.5);
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, "KCMweapons.CrossbowBoltLargeBox");
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, 0.5);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.CrossbowBoltLargeBox");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, "KCMweapons.CrossbowBoltLargeBox");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, 0.5);


-- CrossbowBoltLarge

table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, "KCMweapons.CrossbowBoltLarge");
table.insert(ProceduralDistributions.list["LockerArmyBedroom"].items, 0.5);
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.CrossbowBoltLarge");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 0.5);
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, "KCMweapons.CrossbowBoltLarge");
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, 0.5);
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, "KCMweapons.CrossbowBoltLarge");
table.insert(ProceduralDistributions.list["FirearmWeapons"].items, 0.5);
table.insert(ProceduralDistributions.list["FirearmWeapons"].junk, "KCMweapons.CrossbowBoltLarge");
table.insert(ProceduralDistributions.list["FirearmWeapons"].junk, 0.5);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "KCMweapons.CrossbowBoltLarge");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 0.5);
table.insert(ProceduralDistributions.list["Locker"].items, "KCMweapons.CrossbowBoltLarge");
table.insert(ProceduralDistributions.list["Locker"].items, 0.5);
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "KCMweapons.CrossbowBoltLarge");
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 0.5);
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, "KCMweapons.CrossbowBoltLarge");
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, 0.5);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.CrossbowBoltLarge");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 0.5);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, "KCMweapons.CrossbowBoltLarge");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, 0.5);

-- CrossbowBoltBox

table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.CrossbowBoltBox");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 0.25);
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, "KCMweapons.CrossbowBoltBox");
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, 0.25);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "KCMweapons.CrossbowBoltBox");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 0.25);
table.insert(ProceduralDistributions.list["Locker"].items, "KCMweapons.CrossbowBoltBox");
table.insert(ProceduralDistributions.list["Locker"].items, 0.25);
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "KCMweapons.CrossbowBoltBox");
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, "KCMweapons.CrossbowBoltBox");
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, 0.5);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.CrossbowBoltBox");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 1);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, "KCMweapons.CrossbowBoltBox");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, 0.5);

-- CrossbowBolt

table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, "KCMweapons.CrossbowBolt");
table.insert(ProceduralDistributions.list["CampingStoreBackpacks"].items, 0.5);
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, "KCMweapons.CrossbowBolt");
table.insert(ProceduralDistributions.list["CampingStoreGear"].items, 0.5);
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, "KCMweapons.CrossbowBolt");
table.insert(ProceduralDistributions.list["GarageMetalwork"].items, 0.5);
table.insert(ProceduralDistributions.list["Locker"].items, "KCMweapons.CrossbowBolt");
table.insert(ProceduralDistributions.list["Locker"].items, 0.5);
table.insert(ProceduralDistributions.list["WardrobeMan"].items, "KCMweapons.CrossbowBolt");
table.insert(ProceduralDistributions.list["WardrobeMan"].items, 0.5);
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, "KCMweapons.CrossbowBolt");
table.insert(ProceduralDistributions.list["WardrobeMan"].junk, 0.5);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, "KCMweapons.CrossbowBolt");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].items, 0.5);
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, "KCMweapons.CrossbowBolt");
table.insert(ProceduralDistributions.list["WardrobeRedneck"].junk, 0.5);